import { ThemeTokens, ThemePresetKey } from '../types/theme';

export const themePresets: Record<ThemePresetKey, ThemeTokens> = {
  watercolor_atlas: {
    presetKey: 'watercolor_atlas',
    name: 'Watercolor Atlas (Default)',
    description: 'Fantasy-map visual language featuring ocean blue, teal, sea green, parchment beige, and gold accents.',
    primaryColor: '#2b7a94',       // Ocean Blue
    secondaryColor: '#366e57',     // Sea Green
    accentColor: '#d4af37',        // Compass Gold
    backgroundColor: '#0c1626',     // Deep Navy Night Sky
    panelSurfaceColor: '#132238',   // Deep Parchment Slate
    panelBorderColor: 'rgba(212, 175, 55, 0.25)', // Gold Accent Border
    textColor: '#e2e8f0',
    textMutedColor: '#94a3b8',
    headingColor: '#f8fafc',
    headingFontFamily: "'Cinzel', 'Playfair Display', Georgia, serif",
    bodyFontFamily: "'Plus Jakarta Sans', 'Inter', system-ui, sans-serif",
    textureStrength: 0.15,
    decorativeMotif: 'cartographic',
    borderStyle: 'solid',
    cornerRadius: '1rem',
    shadowStyle: '0 10px 30px -5px rgba(12, 22, 38, 0.8), 0 0 15px rgba(212, 175, 55, 0.1)',
    isDark: true,
  },
  midnight_ocean: {
    presetKey: 'midnight_ocean',
    name: 'Midnight Ocean',
    description: 'Deep oceanic blues and cyan glows for immersive night browsing.',
    primaryColor: '#0ea5e9',
    secondaryColor: '#0284c7',
    accentColor: '#38bdf8',
    backgroundColor: '#030712',
    panelSurfaceColor: '#0f172a',
    panelBorderColor: 'rgba(56, 189, 248, 0.2)',
    textColor: '#f1f5f9',
    textMutedColor: '#64748b',
    headingColor: '#ffffff',
    headingFontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    bodyFontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    textureStrength: 0.0,
    decorativeMotif: 'minimal',
    borderStyle: 'solid',
    cornerRadius: '0.75rem',
    shadowStyle: '0 10px 25px -5px rgba(0, 0, 0, 0.5)',
    isDark: true,
  },
  clean_catalog: {
    presetKey: 'clean_catalog',
    name: 'Clean Catalog (Light)',
    description: 'High-legibility light parchment and indigo for clean daytime curation.',
    primaryColor: '#1e40af',
    secondaryColor: '#047857',
    accentColor: '#b45309',
    backgroundColor: '#f8fafc',
    panelSurfaceColor: '#ffffff',
    panelBorderColor: '#e2e8f0',
    textColor: '#0f172a',
    textMutedColor: '#475569',
    headingColor: '#0f172a',
    headingFontFamily: "'Cinzel', Georgia, serif",
    bodyFontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    textureStrength: 0.05,
    decorativeMotif: 'cartographic',
    borderStyle: 'solid',
    cornerRadius: '0.75rem',
    shadowStyle: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
    isDark: false,
  },
  neon_arcade: {
    presetKey: 'neon_arcade',
    name: 'Neon Arcade',
    description: 'Vibrant cyberpunk neon magenta, cyan, and dark grid aesthetic.',
    primaryColor: '#ec4899',
    secondaryColor: '#06b6d4',
    accentColor: '#f59e0b',
    backgroundColor: '#090514',
    panelSurfaceColor: '#160d29',
    panelBorderColor: 'rgba(236, 72, 153, 0.3)',
    textColor: '#f472b6',
    textMutedColor: '#a78bfa',
    headingColor: '#ffffff',
    headingFontFamily: "'Orbitron', sans-serif",
    bodyFontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    textureStrength: 0.0,
    decorativeMotif: 'neon',
    borderStyle: 'solid',
    cornerRadius: '0.5rem',
    shadowStyle: '0 0 20px rgba(236, 72, 153, 0.25)',
    isDark: true,
  },
  retro_console: {
    presetKey: 'retro_console',
    name: 'Retro Console',
    description: 'Nostalgic 16-bit parchment, warm amber, and classic arcade console vibes.',
    primaryColor: '#d97706',
    secondaryColor: '#059669',
    accentColor: '#dc2626',
    backgroundColor: '#18120c',
    panelSurfaceColor: '#261c14',
    panelBorderColor: 'rgba(217, 119, 6, 0.3)',
    textColor: '#fef3c7',
    textMutedColor: '#d97706',
    headingColor: '#fffbeb',
    headingFontFamily: "'Press Start 2P', monospace, sans-serif",
    bodyFontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    textureStrength: 0.1,
    decorativeMotif: 'retro',
    borderStyle: 'solid',
    cornerRadius: '0.375rem',
    shadowStyle: '4px 4px 0px rgba(0, 0, 0, 0.8)',
    isDark: true,
  },
  forest_explorer: {
    presetKey: 'forest_explorer',
    name: 'Forest Explorer',
    description: 'Natural emerald greens, earthy brown, and gold accents for wilderness maps.',
    primaryColor: '#059669',
    secondaryColor: '#10b981',
    accentColor: '#eab308',
    backgroundColor: '#061a12',
    panelSurfaceColor: '#0d2d20',
    panelBorderColor: 'rgba(16, 185, 129, 0.25)',
    textColor: '#ecfdf5',
    textMutedColor: '#6ee7b7',
    headingColor: '#ffffff',
    headingFontFamily: "'Cinzel', Georgia, serif",
    bodyFontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    textureStrength: 0.1,
    decorativeMotif: 'cartographic',
    borderStyle: 'solid',
    cornerRadius: '1rem',
    shadowStyle: '0 10px 25px -5px rgba(6, 26, 18, 0.7)',
    isDark: true,
  },
};
